on: [push]
name: devops-tp3-workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # login to Azure
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # login to ACR
        - name: 'Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        # lint dockerfile
        - name: 'Hadolint test'
          id: hadolint_test
          run: |
            OUTPUT=$(docker run --rm -i hadolint/hadolint < dockerfile | wc -l)
            echo "::set-output name=OUTPUT::$OUTPUT"
        
        # build and push image to ACR
        - name: 'Build and push image'
          if: steps.hadolint_test.outputs.OUTPUT==0
          run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IDENTIFIANT_EFREI }}:v1
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IDENTIFIANT_EFREI }}:v1
        
        # deploy to ACI
        - name: 'Deploy to Azure Container Instances'
          if: steps.hadolint_test.outputs.OUTPUT==0
          run: az container create --resource-group ${{ secrets.RESOURCE_GROUP }} -f deploy.yaml
          env:
            RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
            IDENTIFIANT_EFREI: devops-${{ secrets.IDENTIFIANT_EFREI }}
            REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
            API_KEY: ${{ secrets.API_KEY }}