on:
  push:
    branches:
      - main
      
name: devops-tp3-workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
      
        # deploy to ACI
        - name: 'Deploy to Azure Container Instances'
          if: steps.hadolint_test.outputs.OUTPUT==0
          run: |
            az container delete --name 20200236 --resource-group ${{ secrets.RESOURCE_GROUP }}