on: [push]
name: devops-tp3-workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # login to Azure
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: AKIAZJY4QHWBJOZNLJFQ
            aws-secret-access-key: fp1e6CyoCWMg45bRXyAPssgZJJNJNKnHpKxfqP
            aws-region: eu-west-3